### ISSUE TITLE
iptable_filter module missing [overo]

### ISSUE THREAD

**Issue by dsayling** [gumstix/live-build#1]
iptables module can't run

```
$ iptables -L
>> iptables v1.4.21: can't initialize iptables table 'filter': Tables does not exist (do you need to insmod?)
$ modprobe ip_tables
$ modprobe iptable_filter
>> modprobe: FATAL: Module iptable_filter not found
```

I tried building the entire netfilter module as an external module from https://github.com/gumstix/linux, but there were numerous build errors.

**Comment by arunbharadwaj** [comment]
I have enabled iptable_filter module in the kernel config and now the iptables command seems to work fine for me. Please give it a try and let me know if it looks OK on your end. Thanks.

**Comment by dsayling** [comment]
Working now. Thanks.
