### ISSUE TITLE
missing ssh keys [overo]

### ISSUE THREAD

**Issue by dsayling** [gumstix/live-build#2]
The ssh keys are missing in the live build and have to be generated locally before an ssh session can be established.

```
$ ssh-keygen -t rsa1 -f /etc/ssh/ssh_host_rsa_key
$ ssh-keygen -t dsa  -f /etc/ssh/ssh_host_dsa_key
```

**Comment by arunbharadwaj** [comment]
This issue is now fixed in master branch.
