### ISSUE TITLE
lxde hangs on boot [duovero]

### ISSUE THREAD

**Issue by fangchangma** [gumstix/live-build#4]
I followed the instructions to make an vivid-lxde image for duovero. The compilation and creation of the bootable image on my microSD card were both ok. However, on boot, nothing shows up on display and when I established a serial connection via the console, I got some the following messages and the system just hangs. Any suggestions?

...
[    3.321533] mmc0: new high speed SDHC card at address b368
[    3.327301] twl_rtc 48070000.i2c:twl@48:rtc: setting system clock to 2000-01-01 00:03:59 UTC (946685039)
[    3.337341] sr_init: No PMIC hook to init smartreflex
[    3.341033] mmcblk0: mmc0:b368       7.45 GiB
[    3.347351] smartreflex smartreflex.0: omap_sr_probe: SmartReflex driver initialized
[    3.347351]  mmcblk0: p1 p2
[    3.359283] smartreflex smartreflex.1: omap_sr_probe: SmartReflex driver initialized
[    3.368164] smartreflex smartreflex.2: omap_sr_probe: SmartReflex driver initialized
[    3.419250] VUSB: disabling
[    3.423065] VANA: disabling
[    3.432769] RAMDISK: Couldn't find valid RAM disk image starting at 0.
[    3.439758] VFS: Cannot open root device "disk/by-label/rootfs" or unknown-block(0,0): error -6
[    3.449127] Please append a correct "root=" boot option; here are the available partitions:
[    3.458160] b300         7822336 mmcblk0  driver: mmcblk
[    3.463775]   b301           65472 mmcblk0p1 00000000-01
[    3.469238]   b302         4128768 mmcblk0p2 00000000-02
[    3.474853] Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)
[    3.483825] CPU1: stopping
[    3.483947] CPU: 1 PID: 0 Comm: swapper/1 Not tainted 3.17.8-custom #1
[    3.483947] [<c00155dc>](unwind_backtrace) from [<c0011d78>](show_stack+0x10/0x14)
[    3.501770] [<c0011d78>](show_stack) from [<c06232e4>](dump_stack+0x84/0x9c)
[    3.501770] [<c06232e4>](dump_stack) from [<c0013ce8>](handle_IPI+0x17c/0x208)
[    3.501770] [<c0013ce8>](handle_IPI) from [<c00086ec>](gic_handle_irq+0x58/0x60)
[    3.501770] [<c00086ec>](gic_handle_irq) from [<c0629c24>](__irq_svc+0x44/0x5c)
[    3.501770] Exception stack(0xed0b1f30 to 0xed0b1f78)
[    3.532836] 1f20:                                     00000001 00000001 00000000 ed08c140
[    3.532836] 1f40: c09c8088 00000000 ced6ddd3 00000000 edfa5158 c092f3f4 00000000 00000001
[    3.532836] 1f60: 00000000 ed0b1f78 c0081ca0 c04c210c 20000153 ffffffff
[    3.562164] [<c0629c24>](__irq_svc) from [<c04c210c>](cpuidle_enter_state+0x124/0x1a0)
[    3.562164] [<c04c210c>](cpuidle_enter_state) from [<c04c3c48>](cpuidle_enter_state_coupled+0x110/0x37c)
[    3.562164] [<c04c3c48>](cpuidle_enter_state_coupled) from [<c0078710>](cpu_startup_entry+0x210/0x2d0)
[    3.580749] [<c0078710>](cpu_startup_entry) from [<80008784>](0x80008784)
[    3.590667] ---[ end Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)

**Comment by yangjiel** [comment]
**Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0).**
It is possible that your SD card is corrupted, did you try using another SD card? Currently I am not working on the vivid-lxde.

**Comment by yangjiel** [comment]
Close for no response. If anyone has the same issue, re-open this or open a new issue and mention a person within the team such we can notice the issue.
