### ISSUE TITLE
kernel fails to compile redefinition of ‘return_address’

### ISSUE THREAD

**Issue by ryanvade** [gumstix/live-build#5]
I am attempting to build an image with Ubuntu 16.04 for an Overo Fire.  I created a new profile and attempted to build. 

```
**arch/arm/kernel/return_address.c:63:2: warning: #warning "TODO: return_address should use unwind tables" [-Wcpp]
 #warning "TODO: return_address should use unwind tables"
  ^
arch/arm/kernel/return_address.c:66:7: error: redefinition of ‘return_address’
 void *return_address(unsigned int level)
       ^
In file included from include/linux/ftrace.h:20:0,
                 from arch/arm/kernel/return_address.c:12:
./arch/arm/include/asm/ftrace.h:48:21: note: previous definition of ‘return_address’ was here
 extern inline void *return_address(unsigned int level)
                     ^
scripts/Makefile.build:257: recipe for target 'arch/arm/kernel/return_address.o' failed
make[4]: *** [arch/arm/kernel/return_address.o] Error 1
Makefile:929: recipe for target 'arch/arm/kernel' failed
make[3]: *** [arch/arm/kernel] Error 2
make[3]: *** Waiting for unfinished jobs....
**
```

 My system is Ubuntu 16.04 with arm-linux-gnueabihf-gcc (Ubuntu/Linaro 5.3.1-14ubuntu2) 5.3.1 20160413

**Comment by arunbharadwaj** [comment]
Ubuntu moved to gcc 5.0 in 15.10 and linux kernel does not yet support building with gcc-5. If you install gcc-4.9 alongside and re-link all the gcc-related sym links in /usr/bin/ to now point to gcc-4.9 binaries instead of 5, you should be able to build the kernel successfully.

**Comment by ryanvade** [comment]
Switching back to gcc4.9 does work.  There are other changes made in 16.04 that break the script, particularly image building.
