### ISSUE TITLE
Wi-Fi issues [duovero]

### ISSUE THREAD

**Issue by ThiagoCM** [gumstix/live-build#6]
Hey guys. 

Any tips for enabling Wi-Fi on a Duovero Zephyr with Parlor expasion board? I've tried nearly everything to enable it on Ubuntu and still not works.

Followed this guide: 
https://github.com/gumstix/live-build/wiki/Enabling-WiFi-on-Gumstix-Ubuntu

edit:
actually, I cannot even use sudo on my Ubuntu image and there's a warning of
[FAILED] Failed to start Load Kernel Modules.
when the booting process was happening

**Comment by yangjiel** [comment]
I don't know why the kernel is not loading modules, I suspect that is the image problem. Can you try this image: [Ubuntu on Duovero](https://gumstix-ubuntu.s3.amazonaws.com/2017-06-22/duovero/master/duovero-vivid-console.img.xz)? After downloading it, unzip and dd it into the SD card.

The instruction I used is
```
$ sudo ifconfig wlan0 up
$ sudo nano /etc/wpa_supplicant.conf
ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
update_config=1

network={
        ssid="wifi name"
        psk="password"
}
$ sudo rm /var/run/wpa_supplicant/wlan0
$ sudo wpa_supplicant -B -iwlan0 -c/etc/wpa_supplicant.conf -Dnl80211
$ sudo dhclient wlan0
```

If you are using the old Duovero COM that doesn't have `wlan` device, please try `mlan` by replacing the `wlan` to `mlan`.

**Comment by yangjiel** [comment]
Any feedback?

**Comment by yinghong91** [comment]
I'm having the same issue, running `sudo ifconfig wlan0 up` returns:

> wlan0: ERROR while getting interface flags: No such device

Running `sudo wpa_supplicant -B -iwlan0 -c/etc/wpa_supplicant.conf -Dnl80211` returns:

> Successfully initialized wpa_supplicant
> Could not read interface wlan0 flags: No such device
> nl80211: Driver does not support authentication/association or connect commands
> Could not read interface wlan0 flags: No such device
> wlan0: Failed to initialize driver interface

I used the image you have provided.

**Comment by yinghong91** [comment]
Okay so instead of `wlan0`, `mlan0` has to be used.
I replaced all the instances of `wlan0` to `mlan0` and it was able to detect the device.
However I still haven't managed to get it working, suspect that it is due to a kernel issue according to [http://gumstix.8.x6.nabble.com/Older-Duoveros-R3921-and-3922-running-3-18-kernel-Problem-with-built-in-Wi-Fi-and-Bluetooth-td4971413.html](url)
I was using the old Duovero Zephyr but I'll be trying out the Zephyr-Y COM soon.

**Comment by yinghong91** [comment]
Okay I tried it out on Duovero Zephyr-Y COM, using method 2 from the guide with wlan0, and it worked.

**Comment by absci** [comment]
I did a test for old Duovero Zephyr COM on 3.18 kernel (Yocto Fido). When grep mwifiex it shows
```
root@duovero:~# dmesg |grep mwifiex
[   10.461639] mwifiex: rx work enabled, cpus 2
[   10.480957] mwifiex_sdio mmc0:0001:1: WLAN FW already running! Skip FW dnld
[   10.488311] mwifiex_sdio mmc0:0001:1: WLAN FW is active
[   10.901824] mwifiex_sdio mmc0:0001:1: driver_version = mwifiex 1.0 (14.66.9.p96) 
[   10.943145] mwifiex_sdio mmc0:0001:1 wlan0: renamed from mlan0
```

So I edited wpa_supplicant.conf and ran wpa_supplicant command, wifi seems good. You could try a Yocto Fido image (https://catalina.gumstix.com/binaries/9927/), it should work you.

**Comment by yangjiel** [comment]
@absci The issue here is about the live-build Ubuntu, instead of Yocto Linux.
